#
#--------------------------------------------------------------------------
# Image Setup.
# 
# See https://github.com/phusion/baseimage-docker/blob/master/Changelog.md 
# for a list of version numbers.
#--------------------------------------------------------------------------
#

FROM phusion/baseimage:bionic-1.0.0

LABEL maintainer="Artem Fufaldin <artem.fufaldin@gmail.com>"

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

#
#--------------------------------------------------------------------------
# Software's Installation
#--------------------------------------------------------------------------
#

# Install "PHP Extentions", "libraries", "Software's"
RUN set -xe; \
    echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -cs) main" | tee -a /etc/apt/sources.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E5267A6C && \
    apt-get update && \
    apt-get -o DPkg::options::="--force-confold" -y upgrade && \
    apt-get -o DPkg::options::="--force-confold" -y install \
        php7.4-common \
        php7.4-bcmath \
        php7.4-cli \
        php7.4-json \
        php7.4-xml \
        php7.4-mbstring

#####################################
# Composer:
#####################################

COPY ./install_composer.sh /root/install_composer.sh
RUN . /root/install_composer.sh

# Clean up
RUN rm /root/install_composer.sh && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*