#
#--------------------------------------------------------------------------
# Image Setup.
# 
# See https://github.com/phusion/baseimage-docker/blob/master/Changelog.md 
# for a list of version numbers.
#--------------------------------------------------------------------------
#

FROM phusion/baseimage:bionic-1.0.0

LABEL maintainer="Artem Fufaldin <artem.fufaldin@gmail.com>"

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

# Install Laravel requirements
RUN set -xe; \
    echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -cs) main" | tee -a /etc/apt/sources.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E5267A6C && \
    apt-get update && \
    apt-get -o DPkg::options::="--force-confold" -y upgrade && \
    apt-get -o DPkg::options::="--force-confold" -y install \
        php7.3-common \
        php7.3-bcmath \
        php7.3-cli \
        php7.3-json \
        php7.3-xml \
        php7.3-mbstring

# Composer
COPY ./install_composer.sh /root/install_composer.sh
RUN . /root/install_composer.sh && \
   rm /root/install_composer.sh

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*